package de.rwth.swc.coffee4j.engine.configuration.extension.generation;

import de.rwth.swc.coffee4j.engine.configuration.model.Combination;
import de.rwth.swc.coffee4j.engine.configuration.extension.Extension;

import java.util.List;

/**
 * Represents a phase callback after the generation phase
 */
@FunctionalInterface
public interface AfterGenerationCallback extends Extension {

    /**
     * Execute the callback with the supplied {@link Combination combinations}.
     * The callback should only modify the order of the {@link Combination combinations},
     * but not the {@link Combination combinations itself}
     *
     * @param inputCombinations the combinations generated by the generation phase
     * @return the possibly sorted {@link Combination combinations} that were inputted
     */
    List<Combination> afterGeneration(List<Combination> inputCombinations);

}
