package de.rwth.swc.coffee4j.engine.configuration.extension.execution;

import de.rwth.swc.coffee4j.engine.configuration.extension.Extension;
import de.rwth.swc.coffee4j.engine.configuration.model.Combination;

import java.util.List;

/**
 * Represents a phase callback before the execution phase
 */
@FunctionalInterface
public interface BeforeExecutionCallback extends Extension {

    /**
     * Execute the callback with the supplied {@link Combination combinations}
     *
     * @param combination the combinations generated by the generation phase
     */
    void beforeExecution(List<Combination> combination);

}
